body:
  - attributes:
      description: What did you expect to happen?
      label: Expected
    type: textarea
    validations:
      required: true
  - attributes:
      description: What happened instead?
      label: Actual
    type: textarea
    validations:
      required: true
  - attributes:
      description: Any additional info you'd like to provide.
      label: Additional Info
    type: textarea
description: Report a bug trying to run the code
labels:
  - "type: bug"
name: 🐛 Bug
title: "🐛 Bug: <short description of the bug>"
