body:
  - attributes:
      description: What did you expect to be able to do?
      label: Overview
    type: textarea
    validations:
      required: true
  - attributes:
      description: Any additional info you'd like to provide.
      label: Additional Info
    type: textarea
description: Request that a new feature be added or an existing feature improved
labels:
  - "type: feature"
name: 🚀 Feature
title: "🚀 Feature: <short description of the feature>"
